Added units explicitly in STIR documentation
SyneRBI/SIRF pull request #1024
Opened 2021-12-01 09:16 UTC by skarrea

Removes ambiguity between quantities expected in physical units
and quantities given in number of voxels.
[ci skip]
[travis skip]

2021-12-01 14:08 UTC, robbietuk requested changes
Looks good! Small gramatical correction.

2021-12-01 14:08 UTC, robbietuk commented on src/xSTIR/pSTIR/STIR.py
> +        """Returns x radius. in mm"""
```suggestion
        """Returns x radius in mm."""
```

2021-12-01 19:00 UTC, skarrea commented on src/xSTIR/pSTIR/STIR.py
> +        """Returns x radius. in mm"""
Thanks, good catch!

2021-12-01 21:23 UTC, KrisThielemans approved these changes
looks good. all done? I think we can squash-merge this

2021-12-02 11:06 UTC, skarrea commented
Yes, all done. Sound good.

2021-12-02 11:17 UTC, merged

2021-12-02 12:44 UTC, KrisThielemans commented
thanks @skarrea !