add version.h generated from the numbers in CMakeLists.txt
SyneRBI/SIRF pull request #1029
Opened 2022-01-12 17:10 UTC by paskino

closes #874

2022-01-15 21:31 UTC, KrisThielemans requested changes
could add another `git_version.h` file from `git describe` as discussed in #874, or leave that for later.

2022-01-15 21:31 UTC, KrisThielemans commented on CMakeLists.txt
> +install(FILES "${CMAKE_CURRENT_BINARY_DIR}/cmake/version.h" DESTINATION "${CMAKE_INSTALL_PREFIX}/include/sirf/common/")
```suggestion
configure_file("cmake/version.h.in" "${CMAKE_CURRENT_BINARY_DIR}/cmake/include/sirf/common/version.h")
install(FILES "${CMAKE_CURRENT_BINARY_DIR}/cmake/include/sirf/common/version.h" DESTINATION "${CMAKE_INSTALL_PREFIX}/include/sirf/common/")
```

2022-01-15 21:31 UTC, KrisThielemans commented on src/common/tests/CMakeLists.txt
> +target_include_directories(test_version PUBLIC ${CMAKE_BINARY_DIR}/cmake)
```suggestion
target_include_directories(test_version PUBLIC ${CMAKE_BINARY_DIR}/cmake/include)
```

2022-01-15 21:31 UTC, KrisThielemans commented on src/common/tests/test_version.cpp
> +#include "version.h"
```suggestion
#include "sirf/common/version.h"
```

2022-01-17 11:19 UTC, paskino commented
I wonder what would be the use of `git_version.h`. It'd add confusion, IMHO.

2022-01-18 15:33 UTC, merged