Trying to set the compiler flag -std properly.
SyneRBI/SIRF pull request #1130
Opened 2022-08-16 15:24 UTC by evgueni-ovtchinnikov

## Changes in this pull request

## Testing performed

## Related issues

Fixes #1129.

## Checklist before requesting a review

- [ ] I have performed a self-review of my code
- [ ] I have added docstrings/doxygen in line with the guidance in the developer guide
- [ ] I have implemented unit tests that cover any new or modified functionality
- [x] The code builds and runs on my machine
- [ ] CHANGES.md has been updated with any functionality change

## Contribution Notes

Please read and adhere to the [contribution guidelines](https://github.com/SyneRBI/SIRF/blob/master/CONTRIBUTING.md).

Please tick the following: 

 - [x] The content of this Pull Request (the Contribution) is intentionally submitted for inclusion in SIRF (the Work) under the terms and conditions of the [Apache-2.0](https://www.apache.org/licenses/LICENSE-2.0) License.

2022-08-16 15:31 UTC, KrisThielemans requested changes

2022-08-16 15:31 UTC, KrisThielemans commented on cmake/SetC++Version.cmake
> +  if (CMAKE_VERSION VERSION_LESS "3.1")
we don't need this as we require a more recent CMake

2022-08-16 17:36 UTC, KrisThielemans reviewed
ok great. let's see if GHA is happy.

Maybe you could revert the white-space changes in `SetC++Version.cmake` then (with a `[ci skip]`), i.e. make it identical to the version `master`.

I'd then squash-merge it, but please edit the default message (which contains all commit messages) to something sensible (also making sure there's no `[ci skip]' in the squash-merge commit message).

2022-08-16 17:41 UTC, evgueni-ovtchinnikov commented
> did it resolve your Gadgetron master problem?

using g++9 for building SIRF did

2022-08-17 10:51 UTC, KrisThielemans approved these changes

2022-08-17 10:51 UTC, KrisThielemans commented
want me to squash-merge?

2022-08-17 10:53 UTC, evgueni-ovtchinnikov commented
@KrisThielemans yes please (I am not sure I understand what you wrote about default message)

2022-08-17 14:26 UTC, merged