Resampler norm
SyneRBI/SIRF pull request #1186
Opened 2023-04-19 13:00 UTC by evgueni-ovtchinnikov

## Changes in this pull request

Implements norm method for NiftyResampler.

## Testing performed

## Related issues

Fixes #1182

## Checklist before requesting a review

- [ ] I have performed a self-review of my code
- [ ] I have added docstrings/doxygen in line with the guidance in the developer guide
- [ ] I have implemented unit tests that cover any new or modified functionality
- [x] The code builds and runs on my machine
- [ ] CHANGES.md has been updated with any functionality change

## Contribution Notes

Please read and adhere to the [contribution guidelines](https://github.com/SyneRBI/SIRF/blob/master/CONTRIBUTING.md).

Please tick the following: 

 - [x] The content of this Pull Request (the Contribution) is intentionally submitted for inclusion in SIRF (the Work) under the terms and conditions of the [Apache-2.0](https://www.apache.org/licenses/LICENSE-2.0) License.

2023-04-21 10:11 UTC, KrisThielemans commented
I realise of course this is WIP, but some comments.

Why do we need the `Wrapped_sptr`? I can see it's convenient to have `norm()` etc on a pointer, but why not simply dereference the `shared_ptr`? I guess I'm missing something. 

Also `BFOperator` could be useful I guess, but in its current form, it could just as well be a lambda function probably.

I'm a bit doubtful of including extra classes just for this purpose. If we do, they'd have to be generalised and put in other places once it works.

2023-04-21 13:55 UTC, evgueni-ovtchinnikov commented
I just tried to keep modifications to `JacobiCG` and `AcquisitionModel` classes minimal. In my implementation of `JacobiCG`, `vector_type` objects are assumed to have certain methods (`dot` and `axpby`, now also `norm`), and shared pointers do not have them. An alternative to my approach would be to assume all `vector_type` objects to be pointers, but I found it to be too restrictive an assumption about the nature of `vector_type`, and it would require changing all current definitions of `BFOperator` and `norm` for acquisition models, whereas introducing a simple wrapper object for shared pointers allowed me to avoid it.

2023-06-06 15:04 UTC, KrisThielemans requested changes
some small suggestions on C++ coding style. However, in the same push please merge `master` back here, such that GitHub Actions can be green :-)

2023-06-06 15:04 UTC, KrisThielemans commented on src/Registration/cReg/NiftyResampler.cpp
> +        std::shared_ptr<ImageData> sptr_id = sptr_im->clone();
```suggestion
        auto sptr_id = this->floating_image_sptr()->clone();
```

2023-07-06 15:06 UTC, merged