Zoom image from template method for ImageData
SyneRBI/SIRF pull request #1285
Opened 2024-08-21 10:25 UTC by samdporter

## Changes in this pull request

Added method for `ImageData` to zoom image using geometrical information from a template image

## Testing performed

Compared `ImageData` zoomed using `zoom_image_from_template()` and `zoom_image()` with manually calculated arguments (although dimensions will be different)

## Related issues

## Checklist before requesting a review

- [x]  I have performed a self-review of my code
- [ ] I have added docstrings/doxygen in line with the guidance in the developer guide
- [ ] I have implemented unit tests that cover any new or modified functionality
- [x] The code builds and runs on my machine
- [ ] CHANGES.md has been updated with any functionality change

## Contribution Notes

Please read and adhere to the [contribution guidelines](https://github.com/SyneRBI/SIRF/blob/master/CONTRIBUTING.md).

Please tick the following: 

 - [x] The content of this Pull Request (the Contribution) is intentionally submitted for inclusion in SIRF (the Work) under the terms and conditions of the [Apache-2.0](https://www.apache.org/licenses/LICENSE-2.0) License.

2025-01-16 12:10 UTC, KrisThielemans requested changes
some comments, but in addition, 
- there are some weird/unnecessary white-space differences.  Please fix/ remove (see the diff on github). Some of this might be caused by editor conventions with tabs vs spaces, but even your own code doesn't like sensible in places.

- add a line to CHANGES.md

2025-01-16 12:10 UTC, KrisThielemans commented on src/xSTIR/cSTIR/include/sirf/STIR/stir_data_containers.h
> +		    const char* const zoom_options_str = "preserve_sum");
naming of parameter would have to be `template_image`. Needs some doxygen as well. Finally, I'd prefer these to be called exactly the same as the Python version. e.g. `zoom_image_as_template`

2025-01-16 12:10 UTC, KrisThielemans commented on src/xSTIR/pSTIR/STIR.py
> +        ### becaus of a bug somewherre
misspellings and indentation problems.

2025-01-16 12:10 UTC, KrisThielemans commented on src/xSTIR/pSTIR/STIR.py
> +    def zoom_image_from_template(self, template, scaling='preserve_sum'):
what about `zoom_image_as_template`?

2025-01-28 20:30 UTC, KrisThielemans reviewed
I still see strange inconsistent indentation in the C/C++ files, but as we currently don't have a way to enforce this, I'm prepared to accept it.

2025-01-28 20:31 UTC, KrisThielemans commented
@evgueni-ovtchinnikov want to review?

2025-01-28 20:33 UTC, KrisThielemans commented
@samdporter could conceivably add a Python test (e.g. zoom, test if geometric_info is the same). Not sure how easy it is, and a lot of this is untested anyway, but I'd appreciate it :-)

2025-01-29 09:56 UTC, evgueni-ovtchinnikov commented on src/xSTIR/cSTIR/cstir.cpp
> +void* cSTIR_ImageData_zoom_image_as_template(void* zoomed_image_ptr, void* template_image_ptr,
`const` missing for `template_image_ptr` (see cstir.h line 199)

2025-01-29 10:03 UTC, evgueni-ovtchinnikov commented on src/xSTIR/pSTIR/STIR.py
> +            zoomed_image.handle, self.handle, scaling))
looks like we need `template_image.handle` here rather than `self.handle`?

2025-01-29 10:07 UTC, evgueni-ovtchinnikov requested changes
please see my comments for cstir.cpp line 1513 and STIR.py line 699

2025-02-27 15:01 UTC, evgueni-ovtchinnikov commented on src/xSTIR/pSTIR/STIR.py
> +            zoomed_image.handle, self.handle, scaling))
maybe not

2025-02-27 15:07 UTC, evgueni-ovtchinnikov approved these changes
looks ok

2025-03-18 14:17 UTC, casperdcl commented on src/xSTIR/cSTIR/cstir.cpp
> -#if STIR_VERSION >= 050100
probably fine to remove this since `STIR_REQUIRED_VERSION` in cmake is currently `6.0`

2025-03-18 14:18 UTC, casperdcl approved these changes

2025-03-18 14:21 UTC, merged