Copy examples demos
SyneRBI/SIRF pull request #872
Opened 2021-02-11 14:53 UTC by paskino

copies the `examples, doc` and `data` directory to the `${CMAKE_INSTALL_PATH}/share/SIRF` directory.

Also corrects `examples_data_path` to use `os` to make path manipulation
`petmr_data_path` calls `examples_data_path`

closes #181 
closes #463

2021-02-11 15:29 UTC, KrisThielemans commented
I'd prefer to install in `${CMAKE_INSTALL_PATH}/share/SIRF-${VERSION_MAJOR}.${VERSION_MINOR}`, (set around [here](https://github.com/SyneRBI/SIRF/blob/41336634af15d83db7afbb57292a7752f6735e07/CMakeLists.txt#L58)). A first step towards adding version numbers...

2021-02-11 16:44 UTC, paskino commented
sure. Is a version string available to Python/MATLAB?

2021-02-11 17:11 UTC, paskino commented
This will now add

```python
import sirf

print (sirf.__version__)
```

It doesn't do anything wrt MATLAB.

2021-02-11 23:51 UTC, KrisThielemans requested changes
we're now using a new env variable `SIRF_INSTALL_PATH`. This is new and should be documented in a few places. It would also need  changes in the SuperBuild `env*sh` scripts.

There's a tricky question with this strategy however. If you're developing, do you want examples_data_path to point to an install directory, or the developer version? Now we force it to the install. I think a better strategy might be to 
```
if SIRF_DATA_PATH exists, use it
else if SIRF_INSTALL_PATH exists, do what you do
else error (or could even hunt in /usr/share and /usr/local/share, but not on Windows...)
```
 that way, the developer can set things as they like.

it would need a similar change for Matlab. Might be easier/better to do this on the C++ level (with a `configure`).

By the way, why are the commits from #871 in this diff?

2021-02-12 07:56 UTC, paskino commented
The `data` directory is copied from SIRF source directory, which for a developer will be the one relative to the branch they are using. So I don't see the difference.

I think this has the benefit of separating the build directory from the install, which is a good step in the way of being able to distribute a binary package.

For the working of MATLAB I have no clue and would need some help.

2021-02-12 13:06 UTC, paskino commented
For both Python and MATLAB, the resolution order for the examples data path is:
1. in the directory pointed by `${SIRF_DATA_PATH}` that can be specified by the user externally
2. in the `${SIRF_INSTALL_PATH}/share/SIRF-<version>`

The version string is set by CMake
* for Python in [`sirf/__init__.py`](https://github.com/paskino/SIRF/blob/copy_examples_demos/cmake/sirf.__init__.py.in#L1)
* for MATLAB in [`examples_data_path.m`](https://github.com/paskino/SIRF/blob/copy_examples_demos/src/common/%2Bsirf/%2BUtilities/examples_data_path.m#L29)

2021-02-12 16:42 UTC, KrisThielemans requested changes
As I wrote, I prefer to install in `share/SIRF-2.0`, i.e. without patch info. If you patch, you don't really think that doc etc is going to change. It's what ITK does for instance. Sadly this means that your current strategy of simply relying on `__version__` would fail (i.e. you'd need to remove the patch). sorry

2021-02-12 16:42 UTC, KrisThielemans commented on CMakeLists.txt
> +set(SHARE_DIR ${CMAKE_INSTALL_PREFIX}/share/SIRF-${VERSION_MAJOR}.${VERSION_MINOR}.${VERSION_PATCH})
```suggestion
set(SHARE_DIR ${CMAKE_INSTALL_PREFIX}/share/SIRF-${VERSION_MAJOR}.${VERSION_MINOR})
```
no patch info (data and doc shouldn't really change (a lot) between patches

2021-02-12 16:42 UTC, KrisThielemans commented on src/common/+sirf/+Utilities/examples_data_path.m
> +    elseif ~isempty(SIRF_PATH)
```suggestion
    elseif ~isempty(SIRF_INSTALL_PATH)
```

2021-02-12 16:42 UTC, KrisThielemans commented on src/common/+sirf/+Utilities/examples_data_path.m
> +        p = [ SIRF_INSTALL_PATH filesep 'share' filesep 'SIRF-@VERSION_MAJOR@.@VERSION_MINOR@.@VERSION_PATCH@' filesep 'data' filesep 'examples' filesep petmr ];
```suggestion
        p = [ SIRF_INSTALL_PATH filesep 'share' filesep 'SIRF-@VERSION_MAJOR@.@VERSION_MINOR@' filesep 'data' filesep 'examples' filesep petmr ];
```

2021-02-12 16:42 UTC, KrisThielemans commented on src/common/CMakeLists.txt
> +  configure_file("${CMAKE_CURRENT_SOURCE_DIR}/+sirf/+SIRF/+Utilities/examples_data_path.m" ${MATLAB_DEST}/+SIRF/+Utilities/examples_data_path.m)
I'd file more comfortable with having a `.m.in` file. Or better: we create a `version.m.in` , and get the info from there

2021-02-12 16:44 UTC, KrisThielemans commented
Could you also add a brief section in https://github.com/SyneRBI/SIRF/blob/master/doc/UserGuide.md, near the end I guess, that talks about the environment variables (used by tests and examples only)?

2021-02-13 23:13 UTC, paskino commented
Once this is approved I'll add the docs

2021-02-14 09:18 UTC, KrisThielemans requested changes
All fine. let's just create `version.m.in` , `version_major.m.in` etc files for matlab, and use those. Like this
```matlab
% return SIRF version string (major.minor.patch)
% Usage:
% version_string = version()
function str = version()
  str = '@VERSION_MAJOR@.@VERSION_MINOR@.@VERSION_PATCH@';
```
and
```matlab
p = fullfile(SIRF_INSTALL_PATH , 'share', ['SIRF-' version_major() '.' version_minor() ], 'data' , 'examples',  petmr);
```

add the doc :smile:, and create an issue to create a `sirf_version` on the C++ side

2021-02-14 10:35 UTC, paskino commented
I believe the UserGuide is a programmer's guide. I cannot easily see where that info could fit. Maybe [here ](https://github.com/SyneRBI/SIRF/blob/master/doc/UserGuide.md#general-notes-of-usage-)but I'll have a think.

The info should go in the [wiki](https://github.com/SyneRBI/SIRF/wiki/Examples).

2021-02-14 11:15 UTC, KrisThielemans commented
>  Maybe here but I'll have a think.

sounds good to me

2021-02-14 16:27 UTC, paskino commented
I added info to the [wiki](https://github.com/SyneRBI/SIRF/wiki/Examples#environment-variables).

2021-02-14 16:31 UTC, merged