Constructor for MR image data from MR acquisition data
SyneRBI/SIRF pull request #934
Opened 2021-06-01 13:37 UTC by johannesmayer

Fixes #933

The following operation is performed:
* for each consistent subsets of k-space a `CFImage` is created and appended. 
* the header is populated based on the first acquisition in each subset

While there are fields in the ISMRMRD XML header of the whole rawdata file comprising all acquisitions, the image headers are populated from the `Acquisition` object to include the geometry information that can vary between different subsets of k-space, for example for different 2D slices.
It is assumed that the `Acquisition` objects in each subset contain the same header information.

2021-06-02 18:56 UTC, KrisThielemans requested changes
Obviously I have no idea if this is correct, but you know what you're doing so I trust you!

some tiny cosmetics therefore only. Do check the copyright statements as well, and add something to CHANGES.md

2021-06-02 18:56 UTC, KrisThielemans commented on src/xGadgetron/cGadgetron/include/sirf/Gadgetron/gadgetron_data_containers.h
> +		GadgetronImagesVector(const MRAcquisitionData& ad, const bool coil_resolved=false);
some doxygen doc please

2021-06-02 18:56 UTC, KrisThielemans commented on src/xGadgetron/cGadgetron/include/sirf/Gadgetron/gadgetron_data_containers.h
> +			GadgetronImagesVector(ad, coil_resolved){}
would it make more sense to have
```suggestion
		CoilSensitivitiesVector(MRAcquisitionData& ad) :
			GadgetronImagesVector(ad, /*coil_resolved=*/true){}
```

2021-06-03 08:52 UTC, KrisThielemans commented
Please addd a test for set-up acquisition model (and maybe even basic recon)

2021-06-08 18:22 UTC, johannesmayer commented on src/xGadgetron/cGadgetron/include/sirf/Gadgetron/gadgetron_data_containers.h
> +			GadgetronImagesVector(ad, coil_resolved){}
done

2021-06-08 18:22 UTC, johannesmayer commented on src/xGadgetron/cGadgetron/include/sirf/Gadgetron/gadgetron_data_containers.h
> +		GadgetronImagesVector(const MRAcquisitionData& ad, const bool coil_resolved=false);
done

2021-06-08 20:49 UTC, KrisThielemans approved these changes
ready to merge from my perspective. @johannesmayer ?

2021-06-09 07:44 UTC, johannesmayer commented
I have found that in the special case of an empty `AcquisitionData` object an exception will be thrown.
So there is the option to
* leave it that way, and say if you don't have any acquired data it makes no sense to set up images from them.
* add some changes to use the k-space dimensions defined in the header to make images, but these won't contain geometry information? 

Which would you prefer?

2021-06-09 07:48 UTC, KrisThielemans commented
I think best to use option 1 (throw an exception). Better safe than sorry.

Of course, this will mean we need to be able to create an `AcquisitionData` from scratch...

2021-06-09 07:48 UTC, KrisThielemans commented
let us know if this needs any more changes then or not. I'd prefer to merge it soon such that it can be used in the SIRF-Exercises

2021-06-09 07:51 UTC, johannesmayer commented
Ok then let's go with option 1, and I think it is good to merge.

2021-06-09 07:59 UTC, merged